changed readme and edited example tf
qbeyond/terraform-google-gcs pull request #1
Opened 2023-01-09 10:51 UTC by QBYMKPI

# Description

As discussed in #(issue) we need to support xxx. Therefore we changed yyy.

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] I have run tests and documented them above
- [ ] I have performed a self-review of my own code
- [ ] I have updated the documentation

2023-01-09 10:56 UTC, QBY-ThimoLimpert requested changes
Please add examples from README as examples in subfolder and reference in Autodocu then.

2023-01-09 11:03 UTC, PLN-Qbeyond approved these changes, later dismissed
Looks Good

2023-01-12 14:37 UTC, QBY-ThimoLimpert requested changes
The examples should point out explicit as possible how do something. So we want to use as few variables (at best none, but the provider isn't that good so `project_id` and `organization_id` are needed often).

And please fix the PR text 🗡️ .

2023-01-12 14:37 UTC, ghost commented on README.md
>  ## Example
Now we got the code for the examples at two points. As valid `.tf`files in examples and in `README`. When the module is changed the examples are hopefully updated, but the `README` is most likely forgotten. Please remove the examples from the static readme and add dynamic using terraform-docs.

2023-01-12 14:37 UTC, ghost commented on examples/basic/main.tf
> +  }
I don't think the basic example needs to include IAM permissions. You can create a separate example.
```suggestion
```

2023-01-12 14:37 UTC, ghost commented on examples/README.md
> +The Key and the Bucket must be in the same location!
I think these belong in the root README instead of examples?

2023-01-12 14:37 UTC, ghost commented on examples/README.md
> +user_project_override = true and billing_project to your desired billing project.\
Isn't it already done in Provider configuration in every example?
```suggestion
```

2023-01-12 14:37 UTC, ghost commented on examples/README.md
> +You can add permissions to your account via https://admin.google.com .\
I would add this as a comment directly in the terraform code where appropriate, so it can't be overlooked.

2023-01-12 14:37 UTC, ghost commented on examples/basic/main.tf
> +  count  = var.organization_domain != "" ? 1 : 0
`organization_domain` is mandatory. I don't think it is necessary to test if the domain is empty, as you will hopefully receive an error from the data object anyway and you code doesn't work without the data resource.

2023-01-12 14:37 UTC, ghost commented on examples/basic/variables.tf
> +}
I would suggest using random resources instead, so the example needs as little input as possible.

2023-01-12 14:37 UTC, ghost commented on examples/basic/variables.tf
> +}
I would suggest using random resources instead, so the example needs as little input as possible.

2023-01-12 14:37 UTC, ghost commented on examples/gcs_notification/main.tf
> +  }
As this example is about notification, the IAM part shouldn't be included
```suggestion
```

2023-01-12 14:37 UTC, ghost commented on examples/gcs_notification/main.tf
> +  notification_config = var.notification_config
It's not helpful to just reference an variable here. The idea of the example is to show an example how to configure notification so you should show that.

2023-01-12 14:37 UTC, ghost commented on examples/gcs_notification/variables.tf
> +}
As this example should showcase notification configuration you shouldn't use a variable.
```suggestion
```

2023-01-12 14:37 UTC, ghost commented on examples/gcs_notification/main.tf
> +
Data object not used
```suggestion
```

2023-01-12 14:37 UTC, ghost commented on examples/kms/main.tf
> +  encryption_key = data.google_kms_crypto_key.default.id
Instead of referencing an KMS i would suggest creating one even though they can't be deleted. But as they belong to a project, creation based on a random name should be okay?

2023-01-12 14:37 UTC, ghost commented on examples/kms/main.tf
> +  }
This example is not about IAM.
```suggestion
```

2023-01-12 14:37 UTC, ghost commented on examples/lifecycle_rules/main.tf
> +  lifecycle_rules = try(var.lifecycle_rules, null)
It not reasonable to just reference an variable when you want to showcase how the lifecycle rules are working.

2023-01-12 14:37 UTC, QBY-ThimoLimpert commented on examples/lifecycle_rules/main.tf
> +  }
This example is not about IAM
```suggestion
```

2023-01-16 07:46 UTC, QBYMKPI commented on examples/README.md
> +user_project_override = true and billing_project to your desired billing project.\
Yes. I thought it would be smart to add a static ReadMe for the examples to know how to get them to work.

2023-01-16 07:47 UTC, QBYMKPI commented on examples/README.md
> +You can add permissions to your account via https://admin.google.com .\
Done on next commit

2023-01-16 07:48 UTC, QBYMKPI commented on README.md
>  ## Example
Removed the examples here.

2023-01-16 07:49 UTC, QBYMKPI commented on examples/README.md
> +The Key and the Bucket must be in the same location!
Done on next commit

2023-01-16 07:50 UTC, QBYMKPI commented on examples/basic/main.tf
> +  }
This is from the github basic example, I just copied it, but I can remove it.

2023-01-16 07:54 UTC, QBYMKPI commented on examples/gcs_notification/main.tf
> +
deleted.

2023-01-16 07:54 UTC, QBYMKPI commented on examples/gcs_notification/main.tf
> +  }
removed.

2023-01-16 07:55 UTC, QBYMKPI commented on examples/gcs_notification/variables.tf
> +}
removed and added configuration to code

2023-01-16 08:09 UTC, QBYMKPI commented on examples/kms/main.tf
> +  }
removed

2023-01-16 08:13 UTC, QBYMKPI commented on examples/lifecycle_rules/main.tf
> +  }
removed

2023-01-16 08:13 UTC, QBYMKPI commented on examples/lifecycle_rules/main.tf
> +  lifecycle_rules = try(var.lifecycle_rules, null)
added configuration here

2023-01-16 09:26 UTC, QBYMKPI commented on examples/kms/main.tf
> +  encryption_key = data.google_kms_crypto_key.default.id
I can change that to creating a KMS, but I was against it, because as you said, it cannot be deleted.

2023-01-18 10:53 UTC, QBY-ThimoLimpert approved these changes

2023-01-18 10:53 UTC, ghost commented on README.md
> +which is automated by Terraform. \
```suggestion
To use an existing encryption key, you have to grant permission to your Cloud Storage Agent which is automated by Terraform.
```

2023-01-18 10:53 UTC, ghost commented on README.md
> +The Key and the Bucket must be in the same location! \
```suggestion
The Key and the Bucket must be in the same location! 
```

2023-01-18 12:25 UTC, merged